feat: added near-sdk-js typedoc
near/near-sdk-js pull request #371
Opened 2023-11-29 22:39 UTC by matiasbenary

## Pre-flight checklist

- [ ] I have read the [Contributing Guidelines on pull requests](https://github.com/near/near-sdk-js/blob/master/CONTRIBUTING.md).
- [ ] Commit messages follow the [conventional commits](https://www.conventionalcommits.org/) spec
- [ ] **If this is a code change**: I have written unit tests.
- [ ] **If this is a new API or substantial change**: the PR has an accompanying issue (closes #0000) and the maintainers have approved on my working plan.

## Motivation

## Test Plan

## Related issues/PRs

2023-11-30 09:40 UTC, gagdiez approved these changes

2023-11-30 09:58 UTC, gagdiez requested changes

2023-11-30 09:58 UTC, gagdiez commented on package.json
> +    "typescript": "5.2.x"
apparently the change in typescript version causes a lint problem, and the typedoc version is not compatible with node v14

2023-12-01 02:51 UTC, ailisp approved these changes
Thank you @matiasbenary

2023-12-01 02:51 UTC, merged